version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    ports:
      - "3001:3001" 
    volumes:
      - .:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    env_file:
      - ./frontend/.env

